### ISSUE TITLE
add learning reference "JavaScript Introduction" from edX

### ISSUE THREAD

**Issue by febriansyahdotid** [surabayajs/website#15]
"type": "Video Course (EN)",
"title": "JavaScript Introduction",
"description": "How to add JavaScript (JS) code in your Web site/Web app, how to debug it, How to make interactive Web sites through the DOM API, How to change the CSS styles of HTML5 elements from JavaScript, How to deal with HTML5 forms, How to make basic graphics and animations using the HTML5 canvas, How to use the basic concepts of ES2016, the last iteration of the language: arrays, functions, loops, basic objects
",
"url": "https://www.edx.org/course/javascript-introduction",

**Comment by grikomsn** [comment]
Modify [`learning.json`](https://github.com/surabayajs/website/blob/master/content/learning.json) file and send a PR 👍
