### ISSUE TITLE
Hacktoberfest 2019

### ISSUE THREAD

**Issue by grikomsn** [SurabayaJS/website#3]
'tis the month of Hacktoberfest 2019. Do improve and fix some things and send your pull requests. 👋🏻

**Comment by divyhshah** [comment]
what you want to improve in this website.

**Comment by grikomsn** [comment]
> what you want to improve in this website.

Anything 😄

**Comment by MaheshKonne** [comment]
I'm getting 403 forbidden issue. Permission denied while pushing :(

**Comment by grikomsn** [comment]
> I'm getting 403 forbidden issue. Permission denied while pushing :(

Did you made a fork and push to the forked repository, or directly pushing to this repository?

**Comment by MaheshKonne** [comment]
I'm pushing to my forked repository. 
Saying 
`remote: Permission to SurabayaJS/website.git denied to MaheshKonne.
fatal: unable to access 'https://github.com/SurabayaJS/website.git/': The requested URL returned error: 403`
